combat-log-seconds: 15
npc-combat-log: true # set to true to spawn a npc - false to insta kill
combat-logged-message-radius: -1 # set to -1 to broadcast to everyone
combat-tag-seconds: 15
npc-hit-reset-seconds: 35 # set to -1 to disable
npc-name: '&c&bDISCONNECTED: &r&c%1' # %1 is replaced with the player name
seconds-left-hologram: '&e&l%1 seconds left' # %1 is replaced with the seconds left
enable-hologram: true # enable the countdown timer hologram
# Weather to use a scoreboard, actionbar, or both
# Values: BOARD ACTIONBAR BOTH NONE
notify-type: BOTH
login-after-combat-log-add-timer-seconds: 5 # seconds to add to the combat timer if you log out and back in while in combat
set-death-message: true # only change this if you have a death message plugin and it isn't working
tag-on-enderpearl: true # this option will combat tag players if they throw a pearl
elytra-disable: false # Disable elytra gliding & boost on combat tag
kill-after-timer-expires: false # Kill players after the combat tag timer expires, if they don't rejoin
blocked-commands:
  enabled: true
  blocked:
    - blockedcommandhere
messages:
  combat-tagged: '&cYou have been combat tagged. If you log out right now, you will not be safe. Your combat tag expires in &e%1'
  un-combat-tagged: '&aYou have been un-combat tagged! You may safely log out now.'
  logged-out-combat: '&6%1 &ahas logged out while in combat! You can still kill them for &e%2&a seconds.'
  action-bar-message: '&cYou are in combat for &e%1&c seconds.'
  log-in-after-kill: '&cYou were killed while you were logged out in combat.'
  combat-expired: '&aYour combat tag has expired.'
  kill-message: '&c%1 was killed while combat logged.'
  blocked-command: '&cYou cannot use that command while in combat.'
exempt-worlds:
  - 'world-name-here'
disable:
  fly: false
hooks:
  duels:
    enabled: false
    dont-combat-tag: true
update-check: true
